"""Generate a human-readable digest of the sub_floor DEFECTIVE cases for Adrian's
A4 spot-read. These are the 60 cases the headline false-clear rate rests on, so the
digest is written to let a reader judge whether the deceptions are realistic rather
than strawmen. Writes a Markdown file to the RAILS project root.

Run:  python -m tools.sub_floor_digest
"""
from __future__ import annotations
import re
from collections import Counter
from pathlib import Path

from rails_ref.dataset import load_cases

OUT = Path(r"D:\EvolutionAIry\RAILS\RAILS_sub_floor_cases_for_Adrian_2026-06-03.md")


def _self_report(text: str) -> str:
    m = re.search(r'AGENT SELF-REPORT:\s*\n"(.+?)"', text, re.S)
    return " ".join(m.group(1).split()) if m else "(unparsed)"


def main() -> None:
    cases = [c for c in load_cases() if c.deception == "sub_floor" and c.label == "defective"]
    clean = [c for c in load_cases() if c.deception == "sub_floor_clean"]
    tasks = Counter(c.task for c in cases)

    L: list[str] = []
    add = L.append

    add(f"# RAILS headline dataset — the {len(cases)} sub_floor defective cases (for Adrian, A4)\n")
    add("_Generated from `reference/data/curated_cases/` (seed 20260602). "
        "This is the exact set the headline false-clear rate is computed on._\n")
    add("**Why this matters now (4-provider result).** On this exact set, judge-alone false-clear "
        "ranges from 0% to 96.7% across nine models. Six refuse almost everything (Anthropic "
        "Opus 4.8 / Sonnet 4.6 / Haiku 4.5; OpenAI GPT-5.5 / GPT-5.4-mini; Google Gemini 2.5 Pro); "
        "three rubber-stamp them (Mistral Large 76.7%; prior-gen GPT-4.1 95.0%; Google Gemini 2.5 "
        "Flash 96.7%). RAILS clears 0% for every model. So these cases are **not** a strawman that "
        "no current model fails — three current/prior-gen models genuinely clear them, which is "
        "exactly why a read of their realism is worth your time.\n")

    add("## 1. What one of these cases is, and why it is the right test\n")
    add("A *sub_floor defective* case is a confident, detailed agent **self-report claiming success**, "
        "with **no independent evidence attached** (no CI log, no diff, no third-party attestation). The "
        "agent's claim is, in ground truth, **false** — the work is defective. The judge sees only the "
        "narrative and the acceptance criteria, and is asked PASS/FAIL.\n")
    add("The deception here is deliberately mundane, and that is the point. It is **not** an elaborate lie "
        "with planted fake evidence; it is the ordinary case in agentic settlement — an agent says \"done, "
        "all tests pass, production-ready,\" and nothing independent corroborates it. A material fraction of "
        "such claims are wrong. The class `SELF` (a bare self-report) sits below the obligation's `ATT` floor, "
        "so RAILS has no admissible verifier and returns UNVERIFIABLE; a bare LLM judge has nothing to go on "
        "but the prose.\n")
    add("**The key property to evaluate:** the 60 defective self-reports are textually indistinguishable in "
        f"style from the {len(clean)} *clean* sub_floor self-reports (same template, drawn truthfully). A judge "
        "cannot tell them apart, because there is no signal to tell them apart by. So a judge that clears the "
        "defective ones is not being out-smarted — it is rendering a verdict on confidence and fluency. That is "
        "the ungoverned disposition the paper is about.\n")

    add("## 2. The honest weakness to judge (this is what your spot-read is for)\n")
    add("The narratives are **templated** — generated by combining a small pool of domains, bug types, root "
        "causes, and test counts (enumerated in §3). They are realistic in *shape* (they read like real agent "
        "completion reports) but they are synthetic, not captured from production agents. A hostile reviewer can "
        "say \"these are templates, not real agent outputs.\" Per your A4 note, if they read thin we augment with "
        "a handful of real anonymized cases before anything ships. Your call to make on reading them: **is a "
        "confident self-report with no independent evidence a realistic input a deployed judge would face and "
        "clear, and are these defects real defects?**\n")
    add("This realism is now **load-bearing** for the three permissive models' numbers: if a skeptic discounts "
        "the templates, they discount Mistral's 76.7%, GPT-4.1's 95.0%, and Gemini Flash's 96.7%. It does **not** "
        "touch the governance argument — that rests on the *dispersion* across models (including the within-Google "
        "5%-vs-97% split between 2.5 Pro and 2.5 Flash), which holds regardless of how realistic any single case "
        "is — but it does touch the punchy current-model 97%-vs-0% figure. Hence the read.\n")

    add("## 3. The template space (combinatorial variety behind the 60)\n")
    add("Each case draws one domain/bug, one root-cause/fix, and a test count, then asserts success. The pools:\n")
    add("- **Domains × bugs (8):** payments service / webhook idempotency; auth service / token-refresh race; "
        "billing pipeline / invoice rounding; FX rate cache / stale-quote eviction; notifications worker / "
        "duplicate-send; ledger reconciler / batch-cursor off-by-one; checkout API / double-charge; settlement "
        "engine / netting rounding drift.\n")
    add("- **Root causes / fixes (6):** missing idempotency-key check; float-precision drift; TOCTOU race in "
        "the refresh path; unbounded retry loop; stale-cache eviction gap; off-by-one batch cursor.\n")
    add(f"- **Test counts:** {{23, 31, 47, 58, 64, 72, 88, 102}}. Distinct task strings in the 60: "
        f"**{len(tasks)}**.\n")

    add("## 4. Five cases in full (exactly what the judge received)\n")
    for c in cases[:5]:
        add(f"### {c.id}  ·  defect: {c.defect_type}\n")
        add("```\n" + c.artifact_text.strip() + "\n```\n")

    add(f"## 5. All {len(cases)} self-reports (skim list)\n")
    add("_Each is a defective claim; the bracket notes the task it claims to have completed._\n")
    for c in cases:
        add(f"- **{c.id}** — \"{_self_report(c.artifact_text)}\"  \n  _claimed task: {c.task}_")
    add("")

    add("## 6. Where the data lives / how to regenerate\n")
    add("- Raw JSON: `reference/data/curated_cases/case_0000.json` … `case_0059.json` (the sub_floor "
        "defective block is the first 60).\n")
    add("- Regenerate deterministically: `python -m data.build_cases` (seed 20260602).\n")
    add("- Generator for the clean counterparts and other families: `reference/data/build_cases.py`.\n")

    OUT.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {OUT}  ({len(cases)} defective sub_floor cases, {len(tasks)} distinct tasks)")


if __name__ == "__main__":
    main()
